In [ ]:
import numpy as np
import pandas as pd

data = pd.read_csv("advertising.csv")

data = data.drop_duplicates()
data.fillna(data.mean(), inplace=True)

features = ["TV", "Radio"]   
target = "Sales"

X = data[features].values
y = data[target].values.reshape(-1, 1)


X_b = np.column_stack((np.ones((len(X), 1)), X))

theta = np.zeros((X_b.shape[1], 1))
lr = 0.00001
epochs = 1000
m = len(y)


for epoch in range(epochs):
    grad = (2/m) * X_b.T @ (X_b @ theta - y)
    theta -= lr * grad
    
    if epoch % 200 == 0:
        loss = np.mean((X_b @ theta - y)**2)
        print(f"Epoch {epoch:4d} | Loss: {loss:.4f}")

y_pred = X_b @ theta
rmse = np.sqrt(np.mean((y - y_pred)**2))

intercept = theta[0][0]
tv_coef = theta[1][0]
radio_coef = theta[2][0]

print(f"Sales = {intercept:.4f} + ({tv_coef:.4f} * TV) + ({radio_coef:.4f} * Radio)")

# for i, f in enumerate(["Intercept"] + features):
#     print(f"{f}: {theta[i][0]:.4f}")

print(f"\nRMSE: {rmse:.3f}")



Epoch    0 | Loss: 56.9804
Epoch  200 | Loss: 6.8641
Epoch  400 | Loss: 6.2331
Epoch  600 | Loss: 6.1859
Epoch  800 | Loss: 6.1785
Sales = 0.0182 + (0.0688 * TV) + (0.1822 * Radio)

RMSE: 2.485


In [ ]:
# import matplotlib.pyplot as plt
# if X.shape[1] == 1:
#     plt.figure(figsize=(7,5))
#     plt.scatter(X, y, color='blue', label='Actual Data')
#     plt.plot(X, y_pred, color='red', label='Regression Line')
#     plt.xlabel(features[0])
#     plt.ylabel(target)
#     plt.title(f'Linear Regression ({features[0]} vs {target})')
#     plt.legend()
#     plt.grid(True, alpha=0.6)
#     plt.show()
# else:
#     plt.figure(figsize=(6,4))
#     plt.scatter(range(len(y)), y, label='Actual', color='blue')
#     plt.plot(range(len(y_pred)), y_pred, label='Predicted', color='red', linewidth=2)
#     plt.title("Actual vs Predicted Sales")
#     plt.xlabel("Samples")
#     plt.ylabel("Sales")
#     plt.legend()
#     plt.grid(alpha=0.4)
#     plt.show()

In [116]:
import numpy as np
import pandas as pd

data = pd.read_csv("CAR DETAILS FROM CAR DEKHO.csv")
print(data.head())
print(data.columns)
print(data.dtypes)

def encode_transmission(x):
    if 'Auto' in x: 
        return 1
    else:
        return 0

if 'transmission' in data.columns:
    data['transmission_enc'] = data['transmission'].apply(encode_transmission)

if 'owner' in data.columns:
    def encode_owner(x):
        if 'First' in x: return 1
        elif 'Second' in x: return 2
        elif 'Third' in x: return 3
        else: return 4
    data['owner_num'] = data['owner'].apply(encode_owner)

print(data.head())

X = data[["year", "owner_num"]].values
y = data["selling_price"].values.reshape(-1, 1)

# Add Bias column
X_b = np.column_stack((np.ones((len(X),1)), X))  

# Initialize Parameters 
theta = np.zeros((X_b.shape[1], 1))
lr=0.0000001
epochs=1000
m = len(y)

#  Gradient Descent Loop
for epoch in range(epochs):
    gradients = (2/m) * X_b.T @ (X_b @ theta - y)
    theta -= lr * gradients

    if epoch % 200 == 0:
        loss = np.mean((X_b @ theta - y)**2)
        print(f"Epoch {epoch:4d} | Loss: {loss:.4f}")


intercept = theta[0][0]
coef_year = theta[1][0]
coef_owner = theta[2][0]

print(f"\nModel: Selling Price = {intercept:.3f} + {coef_year:.3f}*Year + {coef_owner:.3f}*Owner")


y_pred = X_b @ theta
rmse = np.sqrt(np.mean((y - y_pred)**2))
print(f"RMSE: {rmse:.3f}")


                       name  year  selling_price  km_driven    fuel  \
0             Maruti 800 AC  2007          60000      70000  Petrol   
1  Maruti Wagon R LXI Minor  2007         135000      50000  Petrol   
2      Hyundai Verna 1.6 SX  2012         600000     100000  Diesel   
3    Datsun RediGO T Option  2017         250000      46000  Petrol   
4     Honda Amaze VX i-DTEC  2014         450000     141000  Diesel   

  seller_type transmission         owner  
0  Individual       Manual   First Owner  
1  Individual       Manual   First Owner  
2  Individual       Manual   First Owner  
3  Individual       Manual   First Owner  
4  Individual       Manual  Second Owner  
Index(['name', 'year', 'selling_price', 'km_driven', 'fuel', 'seller_type',
       'transmission', 'owner'],
      dtype='object')
name             object
year              int64
selling_price     int64
km_driven         int64
fuel             object
seller_type      object
transmission     object
owner           

In [ ]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score

data = pd.read_csv("Social_Network_Ads.csv")

print("First 5 rows:\n", data.head())
print("\nInfo:\n", data.info())
print("\nMissing values:\n",data.isnull().sum())
data = data.drop_duplicates()
data = data.dropna()

le = LabelEncoder()
data['Gender'] = le.fit_transform(data['Gender'])

print(data.head())
x=data.drop("Purchased",axis=1)
y=data["Purchased"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

se=StandardScaler()

x_train=se.fit_transform(x_train)
x_test=se.transform(x_test)

model=SVC(kernel='linear',random_state=42) #kernel=rbf
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test,y_pred))
print("Recall:",recall_score(y_test,y_pred))
print("F1 Score:",f1_score(y_test,y_pred))



First 5 rows:
     User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 5 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   User ID          400 non-null    int64 
 1   Gender           400 non-null    object
 2   Age              400 non-null    int64 
 3   EstimatedSalary  400 non-null    int64 
 4   Purchased        400 non-null    int64 
dtypes: int64(4), object(1)
memory usage: 15.8+ KB

Info:
 None

Missing values:
 User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64
    User ID  Gender  Age  EstimatedSalary  Purch

In [ ]:
# TP = np.sum((y_test == 1) & (y_pred == 1))
# TN = np.sum((y_test == 0) & (y_pred == 0))
# FP = np.sum((y_test == 0) & (y_pred == 1))
# FN = np.sum((y_test == 1) & (y_pred == 0))

# print("Confusion Matrix:")
# print(np.array([[TN, FP],[FN, TP]]))

# accuracy = (TP + TN) / (TP+TN+FP+FN)
# recall = TP / (TP + FN) if (TP + FN) != 0 else 0
# precision = TP / (TP + FP) if (TP + FP) != 0 else 0
# f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) != 0 else 0

# print("\nMetrics (from scratch):")
# print("Accuracy:", accuracy)
# print("Recall:", recall)
# print("Precision:", precision)
# print("F1-Score:", f1)

In [122]:
import pandas as pd 
import numpy as np
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score


iris=datasets.load_iris()
data=pd.DataFrame(iris.data,columns=iris.feature_names)
data['species']=iris.target

print("\nMissing Values:\n", data.isnull().sum())
data = data.drop_duplicates()
data = data.dropna()

x=data.drop("species",axis=1)
y=data["species"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

se=StandardScaler()
x_train=se.fit_transform(x_train)
x_test=se.transform(x_test)

model=SVC(kernel='linear',random_state=42) #kernel=rbf
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Precision:",precision_score(y_test,y_pred,average='macro'))
print("Recall:",recall_score(y_test,y_pred,average='macro'))
print("F1 Score:",f1_score(y_test,y_pred,average='macro'))


Missing Values:
 sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
species              0
dtype: int64
Confusion Matrix:
 [[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
Accuracy: 0.9666666666666667
Precision: 0.9722222222222222
Recall: 0.9629629629629629
F1 Score: 0.9658994032395567


In [ ]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data['target'] = iris.target

data = data.drop_duplicates()
data = data.dropna()

x=data.drop("target",axis=1)
y=data["target"]

x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

model=DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=2,random_state=42) #"entropy" or "log_loss"
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))


Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [ ]:
# import matplotlib.pyplot as plt
# from sklearn.tree import plot_tree
# plt.figure(figsize=(10, 6))
# plot_tree(
#     dt,
#     filled=True,
#     feature_names=iris.feature_names,
#     class_names=iris.target_names,
#     rounded=True
# )
# plt.title(f"Decision Tree using {dt.criterion.upper()} Criterion")
# plt.show()

In [ ]:

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.ensemble import BaggingClassifier, RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier
from sklearn.tree import DecisionTreeClassifier

iris = load_iris()
data = pd.DataFrame(data=iris.data, columns=iris.feature_names)
data['target'] = iris.target

data = data.drop_duplicates()
data = data.dropna()

x = data.drop('target', axis=1)
y = data['target']

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

model=BaggingClassifier(estimator=DecisionTreeClassifier(),n_estimators=10,random_state=42)
# model=RandomForestClassifier(n_estimators=10,random_state=42)
# model=GradientBoostingClassifier(n_estimators=10,random_state=42)

# model=AdaBoostClassifier(n_estimators=50,learning_rate=0.1,random_state=42)

# model=DecisionTreeClassifier(criterion='gini',max_depth=4,min_samples_split=2,random_state=42) #"entropy" or "log_loss"

model.fit(x_train,y_train)  

y_pred=model.predict(x_test)

print("Confusion Matrix:\n",confusion_matrix(y_test,y_pred))
print("Accuracy:",accuracy_score(y_test,y_pred))
print("Classification Report:\n",classification_report(y_test,y_pred))

Confusion Matrix:
 [[10  0  0]
 [ 0  9  0]
 [ 0  0 11]]
Accuracy: 1.0
Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00         9
           2       1.00      1.00      1.00        11

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30



In [106]:
#43

import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.decomposition import PCA
from sklearn.metrics import accuracy_score, confusion_matrix,  classification_report

iris = load_iris()
df = pd.DataFrame(data=iris.data, columns=iris.feature_names)
df['target'] = iris.target

X = df.drop('target', axis=1)
y = df['target']

print("Shape of X:", X.shape)
print("Classes:", iris.target_names)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

rf = RandomForestClassifier(random_state=42)
rf.fit(X_train, y_train)
y_pred = rf.predict(X_test)

acc_without_pca = accuracy_score(y_test, y_pred)
print("\nAccuracy without PCA:", acc_without_pca)
print("confusion_matrix",confusion_matrix(y_test, y_pred))
print("classification_report",classification_report(y_test, y_pred))

pca = PCA(n_components=2)  
X_pca = pca.fit_transform(X)

X_train_pca, X_test_pca, y_train_pca, y_test_pca = train_test_split(X_pca, y, test_size=0.3, random_state=42)

rf_pca = RandomForestClassifier(random_state=42)
rf_pca.fit(X_train_pca, y_train_pca)
y_pred_pca = rf_pca.predict(X_test_pca)

acc_with_pca = accuracy_score(y_test_pca, y_pred_pca)
print("Accuracy with PCA:", acc_with_pca)
print("confusion_matrix",confusion_matrix(y_test_pca, y_pred_pca))
print("classification_report",classification_report(y_test_pca, y_pred_pca))

print("\nComparison:")
print(f"Without PCA Accuracy: {acc_without_pca:.3f}")
print(f"With PCA Accuracy:    {acc_with_pca:.3f}")
print()


Shape of X: (150, 4)
Classes: ['setosa' 'versicolor' 'virginica']

Accuracy without PCA: 1.0
confusion_matrix [[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       1.00      1.00      1.00        13
           2       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45

Accuracy with PCA: 0.9777777777777777
confusion_matrix [[19  0  0]
 [ 0 13  0]
 [ 0  1 12]]
classification_report               precision    recall  f1-score   support

           0       1.00      1.00      1.00        19
           1       0.93      1.00      0.96        13
           2       1.00      0.92      0.96        13

    accuracy                           0.98        45
   macro avg       0.98      0.97      0.97        45
weighted a

In [123]:
import numpy as np
from sklearn.datasets import load_iris

# --- Load Data ---
iris = load_iris()
X, y = iris.data, iris.target

# --- Add Bias Term ---
Xb = np.column_stack((np.ones(len(X)), X))     # Bias column added
Yb = np.eye(3)[y]                              # One-hot encoded labels (3 classes)


np.random.seed(42)
theta = np.random.randn(Xb.shape[1], 3)        
lr, epochs = 0.1, 1000

def softmax(z):
    e = np.exp(z - z.max(axis=1, keepdims=True))  
    return e / e.sum(axis=1, keepdims=True)

def compute_loss(Yb, y_pred):
    return -np.mean(np.sum(Yb* np.log(y_pred + 1e-9), axis=1))

for i in range(epochs):
    y_pred = softmax(Xb @ theta)                # forward pass
    loss = compute_loss(Yb, y_pred)             # compute loss
    grad = Xb.T @ (y_pred - Yb) / len(Xb)       # gradient
    theta -= lr * grad                          # update weights

    if i % 200 == 0:
        print(f"Epoch {i:4d} | Loss: {loss:.4f}")

pred = np.argmax(softmax(Xb @ theta), axis=1)
acc = np.mean(pred == y)
print(f"\n Final Accuracy: {acc*100:.2f}%")


Epoch    0 | Loss: 13.4290
Epoch  200 | Loss: 0.2659
Epoch  400 | Loss: 0.1929
Epoch  600 | Loss: 0.1596
Epoch  800 | Loss: 0.1401

 Final Accuracy: 98.00%
